# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Home_page_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=30)),
                ('Hpic', models.ImageField(blank=True, upload_to=b'')),
                ('Dis', models.TextField(blank=True)),
                ('_active', models.CharField(blank=True, max_length=30)),
                ('Name', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Place_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Pics', models.ImageField(blank=True, upload_to=b'')),
                ('Discription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Roomz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=30)),
                ('Occupants', models.IntegerField(blank=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('RoomPics', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Social_ps',
            fields=[
                ('home_page_pics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='details.Home_page_pics')),
            ],
            bases=('details.home_page_pics',),
        ),
        migrations.AddField(
            model_name='place_details',
            name='Room',
            field=models.ForeignKey(default=id, on_delete=django.db.models.deletion.CASCADE, to='details.Roomz'),
        ),
    ]
