# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Home_page_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hpic', models.ImageField(blank=True, upload_to=b'')),
                ('Dis', models.TextField()),
                ('_active', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Place_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Pics', models.ImageField(blank=True, upload_to=b'')),
                ('Discription', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SOcial_ps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spic', models.ImageField(blank=True, upload_to=b'')),
                ('dis', models.TextField(blank=True)),
                ('_ctive', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
