# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_details',
            name='pics',
        ),
        migrations.AddField(
            model_name='place_details',
            name='Pics',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='place_details',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
