# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place_details',
            name='Room',
        ),
        migrations.AddField(
            model_name='place_details',
            name='Room',
            field=models.ManyToManyField(to='details.Roomz'),
        ),
    ]
