# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_social_ps_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_ps',
            name='id',
        ),
        migrations.AddField(
            model_name='social_ps',
            name='home_page_pics_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='details.Home_page_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home_page_pics',
            name='Dis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='home_page_pics',
            name='_active',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
