# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-26 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20160619_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_page_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hpic', models.ImageField(blank=True, upload_to=b'')),
                ('Dis', models.TextField()),
                ('_active', models.CharField(max_length=30)),
            ],
        ),
    ]
