# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20160706_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_ps',
            name='Spic',
        ),
        migrations.RemoveField(
            model_name='social_ps',
            name='_ctive',
        ),
        migrations.RemoveField(
            model_name='social_ps',
            name='dis',
        ),
    ]
