# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20160706_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_ps',
            name='Name',
        ),
        migrations.AddField(
            model_name='home_page_pics',
            name='Name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
