# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20160711_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_page_pics',
            options={'ordering': ['Name']},
        ),
    ]
